version: '3.8'
services: 
    portfolio:
      container_name: portfolio
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
        - './v4:/usr/app'
        - '/usr/app/node_modules'
      ports:
        - '8000:8000'
      environment:
        - CHOKIDAR_USEPOLLING=true
    # host the application to digital ocean domain jenny.com



